name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: macos-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build screensaver
      run: make build

    - name: Verify build output
      run: |
        if [ ! -d "build/LiveScreensaver.saver" ]; then
          echo "Build failed: LiveScreensaver.saver not found"
          exit 1
        fi
        echo "Build successful"
        ls -la build/

    - name: Create ZIP archive
      run: |
        cd build
        zip -r LiveScreensaver.saver.zip LiveScreensaver.saver
        cd ..
        mv build/LiveScreensaver.saver.zip .

    - name: Update Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: latest
        name: Latest Build
        files: LiveScreensaver.saver.zip
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
